### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by Majawat** [th0rn0/lanops-manager#81]
I tried this docker-compse on unRAID and within Docker Desktop on Windows. Either way, I get it all installed and going to http://localhost or https://localhost just gives me a "404 page not found" error.

**Comment by mazzo-** [comment]
same here

**Comment by Apfelwurm** [comment]
@Majawat @mazzorini this version of eventula is currently out of date. If you want, you can take a look on https://github.com/Lan2Play/eventula-manager, until we (hopefully someday) can merge all the changes to upstream. 
It is now on docker hub as well and the docs will be also available online in the next weeks, until then take a look into the docs folder.
